development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: myapp
  password: password1
